### ISSUE TITLE
Có nên dùng React Router để tạo url cho từng game không?

### ISSUE THREAD

**Issue by KooYooMan** [KooYooMan/Fraction#2]

**Comment by thedblaster** [comment]
Với số lượng chơi là 5 màn cùng cấu trúc toàn bộ trang không quá phức tạp, mình nghĩ việc sử dụng React Router là không thật sự cần thiết. Tuy nhiên để có thêm hiểu biết cũng như khiến cho các tương tác của trang được rõ ràng hơn thì mình nghĩ vẫn nên dùng
